Update CI for ITK 5.2
InsightSoftwareConsortium/itkwidgets pull request #409
Opened 2021-04-06 17:00 UTC by tbirdso

- Update CI for ITK v5.2 release
- Drop CI checks for Python 3.5 which is no longer maintained

2021-04-06 17:37 UTC, tbirdso commented
I think failures stem from an issue with an outdated `itk-meshtopolydata` package -- seeing an `ImportError` resulting from changes that are present in ITK 5.2:
>  from itk.support import itkHelpers
E   ImportError: cannot import name 'itkHelpers' from 'itk.support' (unknown location)

@thewtex Given that checks are passing, do we need to publish an updated `itk-meshtopolydata` package for 5.2 compatibility?

2021-04-12 13:23 UTC, tbirdso commented
Observed `PyVectorContainer` failures are due to template changes for the `itk::PyVectorContainer` class introduced in ITK 5.2.0 to align more closely with the `itk::VectorContainer` class. See [PR 408](https://github.com/InsightSoftwareConsortium/itkwidgets/pull/408).

2021-04-12 15:33 UTC, tbirdso commented
Note integration failures predate these changes -- see [Run 2099157846](https://github.com/InsightSoftwareConsortium/itkwidgets/runs/2099157846)

2021-04-16 21:46 UTC, thewtex requested changes

2021-04-16 21:46 UTC, thewtex commented on .github/workflows/build-test.yml
> +        python-version: [3.6, 3.7, 3.8]
Can we add 3.9 here?

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +            point_values = itk.array_from_vector_container(points)
Nice :-)

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +            # Accommodate PyVectorContainer legacy wrapping for element type only
Let's only support the latest version.

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +                # Accommodate PyVectorContainer legacy wrapping for element type only
Remove

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +            # Accommodate PyVectorContainer legacy wrapping for element type only
Remove

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +                else:
Remove

2021-04-16 21:46 UTC, thewtex commented on itkwidgets/_transform_types.py
> +            else:
Remove

2021-04-18 00:54 UTC, tbirdso commented on .github/workflows/build-test.yml
> +        python-version: [3.6, 3.7, 3.8]
Added.

2021-04-18 02:40 UTC, thewtex approved these changes
@tbirdso thanks!

2021-04-18 02:40 UTC, merged