feat(choose-UI): Add capabilities to choose a different UI
InsightSoftwareConsortium/itkwidgets pull request #477
Opened 2022-07-20 22:25 UTC by labdala

**Under construction**

Adds the possibility of choosing a different UI (e.g., itk-viewer-bootstrap-ui) to the itkwidgets version 1.0a5.

2022-07-21 12:27 UTC, thewtex commented on itkwidgets/viewer.py
> +    def __init__(self, ui_collapsed=True, rotate=False, UI='pydata-sphinx', **add_data_kwargs):
`UI` -> `ui`

2022-07-26 18:44 UTC, thewtex requested changes

2022-07-26 18:44 UTC, thewtex commented on itkwidgets/viewer.py
> +             config={}
Please run `black` for styling

2022-07-26 18:44 UTC, thewtex commented on itkwidgets/viewer.py
> +    def __init__(self, ui_collapsed=True, rotate=False, ui='reference', **add_data_kwargs):
`pydata-sphinx` as the default

2022-07-26 19:21 UTC, thewtex requested changes

2022-07-26 19:21 UTC, thewtex commented on itkwidgets/viewer.py
> +        ui = self._init_viewer_kwargs.get('config', None)
'config' -> 'ui'

2022-07-26 19:21 UTC, thewtex commented on itkwidgets/viewer.py
> +        self.viewer_rpc = ViewerRPC(ui_collapsed=ui_collapsed, rotate=rotate, config=ui, **add_data_kwargs)
'config' -> 'ui'

2022-07-26 19:21 UTC, thewtex commented on itkwidgets/integrations/__init__.py
> +async def _set_viewer_image(itk_viewer, image, config, name=None):
remove `config`

2022-07-26 19:21 UTC, thewtex commented on itkwidgets/viewer.py
>          data, input_type = self._get_input_data()
move this above `createWindow` and pass in `data` to `ctx`

2022-07-28 18:14 UTC, labdala commented
Changes addressed in #482.

2022-07-28 18:14 UTC, closed without merging