ENH: Add support for itk.PointSet
InsightSoftwareConsortium/itkwidgets pull request #597
Opened 2023-01-08 17:11 UTC by bnmajor

Fixes #595

2023-01-08 22:06 UTC, thewtex requested changes
@bnmajor thank you! 

Could we also please add a test notebook?

Perhaps an example from the master branch or an adaptation of https://examples.itk.org/src/core/transform/deformavolumewithathinplatespline/documentation?highlight=plate ?

2023-01-08 22:06 UTC, thewtex commented on itkwidgets/integrations/__init__.py
> +            print(f'isinstance(data, itk.PointSet)', flush=True)
remove debug code

2023-01-10 19:57 UTC, bnmajor commented on itkwidgets/integrations/__init__.py
> +            print(f'isinstance(data, itk.PointSet)', flush=True)
Fixed, thanks!

2023-01-12 14:23 UTC, thewtex approved these changes
@bnmajor thanks!!

2023-01-12 14:23 UTC, merged