Do not use CellWatcher outside of notebook env
InsightSoftwareConsortium/itkwidgets pull request #726
Opened 2023-12-29 21:16 UTC by bnmajor

2024-01-02 16:00 UTC, thewtex requested changes
@bnmajor thanks!

Minor refactor requested inline.

2024-01-02 16:00 UTC, thewtex commented on itkwidgets/viewer.py
>  _codecs_registered = False
Can we have something like:

```
_cell_watcher = None
if ENVIRONMENT is not Env.HYPHA:
    _cell_watcher = CellWatcher() # Instantiate the singleton class right away

[...]
# CellWatcher().add_viewer(self.parent) to
_cell_watcher and _cell_watcher.add_viewer(self.parent)
```

2024-01-03 16:02 UTC, bnmajor commented on itkwidgets/viewer.py
>  _codecs_registered = False
Sure thing!

2024-01-03 19:16 UTC, thewtex approved these changes
:100:

2024-01-03 19:16 UTC, merged